pipeline {
    agent any

    tools {
        maven "M2_HOME"
    }

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/vatsanTraining/jenkins_lab.git'
                dir('first-jenkins-pipeline'){
                  bat 'mvn -Dmaven.test.failure.ignore=true clean package'
                }
            }

            post {
                success {
                    archiveArtifacts 'first-jenkins-pipeline/target/*.jar'
                }
            }
        }
    }
}
